spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bookkeeping?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 871870
        driver-class-name: com.mysql.cj.jdbc.Driver

    mail:
        host: smtp.gmail.com
        port: 587
        username: c29740234@gmail.com         # 你的 Gmail 邮箱地址
        password: zjcs jyom hcip lokv     # 应用专用密码（请确保这是正确的应用密码）
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true                     # 启用 STARTTLS
                        required: true                   # 强制要求 STARTTLS
                    connectiontimeout: 5000            # 连接超时（毫秒）
                    timeout: 5000                      # 读取超时（毫秒）
                    writetimeout: 5000                 # 写入超时（毫秒）
    # flyway:
    #     locations: classpath:db/migration
    #     baseline-on-migrate: true
    #     enabled: true

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.jngyen.bookkeeping.backend.pojo.po
logging:
    config: classpath:log4j2.xml
    level:
        root: WARN
