INSERT INTO currency_reference (code, name, symbol, decimal_places, gmt_create, gmt_modified) VALUES
('AED', 'United Arab Emirates Dirham', 'د.إ', 2, NOW(), NOW()),
('AFN', 'Afghan Afghani', '؋', 2, NOW(), NOW()),
('ALL', 'Albanian Lek', 'L', 2, NOW(), NOW()),
('AMD', 'Armenian Dram', '֏', 2, NOW(), NOW()),
('ANG', 'Netherlands Antillean Guilder', 'ƒ', 2, NOW(), NOW()),
('AOA', 'Angolan Kwanza', 'Kz', 2, NOW(), NOW()),
('ARS', 'Argentine Peso', '$', 2, NOW(), NOW()),
('AUD', 'Australian Dollar', 'A$', 2, NOW(), NOW()),
('AWG', 'Aruban Florin', 'ƒ', 2, NOW(), NOW()),
('AZN', 'Azerbaijani Manat', '₼', 2, NOW(), NOW()),
('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', 2, NOW(), NOW()),
('BBD', 'Barbadian Dollar', 'Bds$', 2, NOW(), NOW()),
('BDT', 'Bangladeshi Taka', '৳', 2, NOW(), NOW()),
('BGN', 'Bulgarian Lev', 'лв', 2, NOW(), NOW()),
('BHD', 'Bahraini Dinar', '.د.ب', 3, NOW(), NOW()),
('BIF', 'Burundian Franc', 'FBu', 0, NOW(), NOW()),
('BMD', 'Bermudian Dollar', 'BD$', 2, NOW(), NOW()),
('BND', 'Brunei Dollar', 'B$', 2, NOW(), NOW()),
('BOB', 'Bolivian Boliviano', 'Bs.', 2, NOW(), NOW()),
('BRL', 'Brazilian Real', 'R$', 2, NOW(), NOW()),
('BSD', 'Bahamian Dollar', 'B$', 2, NOW(), NOW()),
('BTN', 'Bhutanese Ngultrum', 'Nu.', 2, NOW(), NOW()),
('BWP', 'Botswana Pula', 'P', 2, NOW(), NOW()),
('BYN', 'Belarusian Ruble', 'Br', 2, NOW(), NOW()),
('BZD', 'Belize Dollar', 'BZ$', 2, NOW(), NOW()),
('CAD', 'Canadian Dollar', 'C$', 2, NOW(), NOW()),
('CDF', 'Congolese Franc', 'FC', 2, NOW(), NOW()),
('CHF', 'Swiss Franc', 'CHF', 2, NOW(), NOW()),
('CLP', 'Chilean Peso', '$', 0, NOW(), NOW()),
('CNY', 'Chinese Yuan', '¥', 2, NOW(), NOW()),
('COP', 'Colombian Peso', '$', 2, NOW(), NOW()),
('CRC', 'Costa Rican Colón', '₡', 2, NOW(), NOW()),
('CUP', 'Cuban Peso', '$', 2, NOW(), NOW()),
('CVE', 'Cape Verdean Escudo', '$', 2, NOW(), NOW()),
('CZK', 'Czech Koruna', 'Kč', 2, NOW(), NOW()),
('DJF', 'Djiboutian Franc', 'Fdj', 0, NOW(), NOW()),
('DKK', 'Danish Krone', 'kr', 2, NOW(), NOW()),
('DOP', 'Dominican Peso', 'RD$', 2, NOW(), NOW()),
('DZD', 'Algerian Dinar', 'د.ج', 2, NOW(), NOW()),
('EGP', 'Egyptian Pound', '£', 2, NOW(), NOW()),
('ERN', 'Eritrean Nakfa', 'Nfk', 2, NOW(), NOW()),
('ETB', 'Ethiopian Birr', 'Br', 2, NOW(), NOW()),
('EUR', 'Euro', '€', 2, NOW(), NOW()),
('FJD', 'Fijian Dollar', '$', 2, NOW(), NOW()),
('FKP', 'Falkland Islands Pound', '£', 2, NOW(), NOW()),
('FOK', 'Faroese Króna', 'kr', 2, NOW(), NOW()),
('GBP', 'British Pound Sterling', '£', 2, NOW(), NOW()),
('GEL', 'Georgian Lari', '₾', 2, NOW(), NOW()),
('GGP', 'Guernsey Pound', '£', 2, NOW(), NOW()),
('GHS', 'Ghanaian Cedi', '₵', 2, NOW(), NOW()),
('GIP', 'Gibraltar Pound', '£', 2, NOW(), NOW()),
('GMD', 'Gambian Dalasi', 'D', 2, NOW(), NOW()),
('GNF', 'Guinean Franc', 'FG', 0, NOW(), NOW()),
('GTQ', 'Guatemalan Quetzal', 'Q', 2, NOW(), NOW()),
('GYD', 'Guyanese Dollar', '$', 2, NOW(), NOW()),
('HKD', 'Hong Kong Dollar', 'HK$', 2, NOW(), NOW()),
('HNL', 'Honduran Lempira', 'L', 2, NOW(), NOW()),
('HRK', 'Croatian Kuna', 'kn', 2, NOW(), NOW()),
('HTG', 'Haitian Gourde', 'G', 2, NOW(), NOW()),
('HUF', 'Hungarian Forint', 'Ft', 2, NOW(), NOW()),
('IDR', 'Indonesian Rupiah', 'Rp', 2, NOW(), NOW()),
('ILS', 'Israeli New Shekel', '₪', 2, NOW(), NOW()),
('IMP', 'Isle of Man Pound', '£', 2, NOW(), NOW()),
('INR', 'Indian Rupee', '₹', 2, NOW(), NOW()),
('IQD', 'Iraqi Dinar', 'ع.د', 3, NOW(), NOW()),
('IRR', 'Iranian Rial', '﷼', 0, NOW(), NOW()),
('ISK', 'Icelandic Króna', 'kr', 0, NOW(), NOW()),
('JEP', 'Jersey Pound', '£', 2, NOW(), NOW()),
('JMD', 'Jamaican Dollar', 'J$', 2, NOW(), NOW()),
('JOD', 'Jordanian Dinar', 'د.ا', 3, NOW(), NOW()),
('JPY', 'Japanese Yen', '¥', 0, NOW(), NOW()),
('KES', 'Kenyan Shilling', 'KSh', 2, NOW(), NOW()),
('KGS', 'Kyrgyzstani Som', 'с', 2, NOW(), NOW()),
('KHR', 'Cambodian Riel', '៛', 2, NOW(), NOW()),
('KID', 'Kiribati Dollar', '$', 2, NOW(), NOW()),
('KMF', 'Comorian Franc', 'CF', 0, NOW(), NOW()),
('KRW', 'South Korean Won', '₩', 0, NOW(), NOW()),
('KWD', 'Kuwaiti Dinar', 'د.ك', 3, NOW(), NOW()),
('KYD', 'Cayman Islands Dollar', 'CI$', 2, NOW(), NOW()),
('KZT', 'Kazakhstani Tenge', '₸', 2, NOW(), NOW()),
('LAK', 'Lao Kip', '₭', 2, NOW(), NOW()),
('LBP', 'Lebanese Pound', 'ل.ل', 2, NOW(), NOW()),
('LKR', 'Sri Lankan Rupee', 'Rs', 2, NOW(), NOW()),
('LRD', 'Liberian Dollar', '$', 2, NOW(), NOW()),
('LSL', 'Lesotho Loti', 'L', 2, NOW(), NOW()),
('LYD', 'Libyan Dinar', 'ل.د', 3, NOW(), NOW()),
('MAD', 'Moroccan Dirham', 'د.م.', 2, NOW(), NOW()),
('MDL', 'Moldovan Leu', 'L', 2, NOW(), NOW()),
('MGA', 'Malagasy Ariary', 'Ar', 2, NOW(), NOW()),
('MKD', 'Macedonian Denar', 'ден', 2, NOW(), NOW()),
('MMK', 'Myanmar Kyat', 'K', 2, NOW(), NOW()),
('MNT', 'Mongolian Tögrög', '₮', 2, NOW(), NOW()),
('MOP', 'Macanese Pataca', 'MOP$', 2, NOW(), NOW()),
('MRU', 'Mauritanian Ouguiya', 'UM', 2, NOW(), NOW()),
('MUR', 'Mauritian Rupee', '₨', 2, NOW(), NOW()),
('MVR', 'Maldivian Rufiyaa', 'ރ.', NOW(), NOW())

-- 2由于篇幅较长，插入全部货币数据的 SQL 语句需要分段完成，以下是第一部分数据注入，您可以按顺序继续注入。


INSERT INTO currency_reference (code, name, symbol, decimal_places, gmt_create, gmt_modified) VALUES
('MWK', 'Malawian Kwacha', 'MK', 2, NOW(), NOW()),
('MXN', 'Mexican Peso', '$', 2, NOW(), NOW()),
('MYR', 'Malaysian Ringgit', 'RM', 2, NOW(), NOW()),
('MZN', 'Mozambican Metical', 'MT', 2, NOW(), NOW()),
('NAD', 'Namibian Dollar', 'N$', 2, NOW(), NOW()),
('NGN', 'Nigerian Naira', '₦', 2, NOW(), NOW()),
('NIO', 'Nicaraguan Córdoba', 'C$', 2, NOW(), NOW()),
('NOK', 'Norwegian Krone', 'kr', 2, NOW(), NOW()),
('NPR', 'Nepalese Rupee', '₨', 2, NOW(), NOW()),
('NZD', 'New Zealand Dollar', 'NZ$', 2, NOW(), NOW()),
('OMR', 'Omani Rial', 'ر.ع.', 3, NOW(), NOW()),
('PAB', 'Panamanian Balboa', 'B/.', 2, NOW(), NOW()),
('PEN', 'Peruvian Sol', 'S/', 2, NOW(), NOW()),
('PGK', 'Papua New Guinean Kina', 'K', 2, NOW(), NOW()),
('PHP', 'Philippine Peso', '₱', 2, NOW(), NOW()),
('PKR', 'Pakistani Rupee', '₨', 2, NOW(), NOW()),
('PLN', 'Polish Zloty', 'zł', 2, NOW(), NOW()),
('PYG', 'Paraguayan Guarani', '₲', 0, NOW(), NOW()),
('QAR', 'Qatari Rial', 'ر.ق', 2, NOW(), NOW()),
('RON', 'Romanian Leu', 'lei', 2, NOW(), NOW()),
('RSD', 'Serbian Dinar', 'дин.', 2, NOW(), NOW()),
('RUB', 'Russian Ruble', '₽', 2, NOW(), NOW()),
('RWF', 'Rwandan Franc', 'FRw', 0, NOW(), NOW()),
('SAR', 'Saudi Riyal', 'ر.س', 2, NOW(), NOW()),
('SBD', 'Solomon Islands Dollar', 'SI$', 2, NOW(), NOW()),
('SCR', 'Seychellois Rupee', '₨', 2, NOW(), NOW()),
('SDG', 'Sudanese Pound', 'ج.س.', 2, NOW(), NOW()),
('SEK', 'Swedish Krona', 'kr', 2, NOW(), NOW()),
('SGD', 'Singapore Dollar', 'S$', 2, NOW(), NOW()),
('SHP', 'Saint Helena Pound', '£', 2, NOW(), NOW()),
('SLL', 'Sierra Leonean Leone', 'Le', 2, NOW(), NOW()),
('SOS', 'Somali Shilling', 'Sh', 2, NOW(), NOW()),
('SRD', 'Surinamese Dollar', '$', 2, NOW(), NOW()),
('SSP', 'South Sudanese Pound', '£', 2, NOW(), NOW()),
('STN', 'São Tomé and Príncipe Dobra', 'Db', 2, NOW(), NOW()),
('SYP', 'Syrian Pound', '£', 2, NOW(), NOW()),
('SZL', 'Swazi Lilangeni', 'E', 2, NOW(), NOW()),
('THB', 'Thai Baht', '฿', 2, NOW(), NOW()),
('TJS', 'Tajikistani Somoni', 'ЅМ', 2, NOW(), NOW()),
('TMT', 'Turkmenistani Manat', 'm', 2, NOW(), NOW()),
('TND', 'Tunisian Dinar', 'د.ت', 3, NOW(), NOW()),
('TOP', 'Tongan Paʻanga', 'T$', 2, NOW(), NOW()),
('TRY', 'Turkish Lira', '₺', 2, NOW(), NOW()),
('TTD', 'Trinidad and Tobago Dollar', 'TT$', 2, NOW(), NOW()),
('TVD', 'Tuvaluan Dollar', '$', 2, NOW(), NOW()),
('TZS', 'Tanzanian Shilling', 'Sh', 2, NOW(), NOW()),
('UAH', 'Ukrainian Hryvnia', '₴', 2, NOW(), NOW()),
('UGX', 'Ugandan Shilling', 'USh', 0, NOW(), NOW()),
('USD', 'United States Dollar', '$', 2, NOW(), NOW()),
('UYU', 'Uruguayan Peso', '$U', 2, NOW(), NOW()),
('UZS', 'Uzbekistani Som', 'soʻm', 2, NOW(), NOW()),
('VES', 'Venezuelan Bolívar', 'Bs.', 2, NOW(), NOW()),
('VND', 'Vietnamese Đồng', '₫', 0, NOW(), NOW()),
('VUV', 'Vanuatu Vatu', 'Vt', 0, NOW(), NOW()),
('WST', 'Samoan Tala', 'T$', 2, NOW(), NOW()),
('XAF', 'CFA Franc BEAC', 'FCFA', 0, NOW(), NOW()),
('XCD', 'East Caribbean Dollar', '$', 2, NOW(), NOW()),
('XOF', 'CFA Franc BCEAO', 'CFA', 0, NOW(), NOW()),
('XPF', 'CFP Franc', '₣', 0, NOW(), NOW()),
('YER', 'Yemeni Rial', '﷼', 2, NOW(), NOW()),
('ZAR', 'South African Rand', 'R', 2, NOW(), NOW()),
('ZMW', 'Zambian Kwacha', 'ZK', 2, NOW(), NOW()),
('ZWL', 'Zimbabwean Dollar', 'Z$', 2, NOW(), NOW());
